# Generated by Django 4.2.2 on 2023-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
