# Generated by Django 4.2.2 on 2023-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='product_quantiity',
            new_name='product_quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
    ]
